/**
 * Supported languages for agent response language preference.
 * Single source of truth — used by desktop UI and daemon routing.
 */

export const SUPPORTED_LANGUAGES = [
  { code: 'auto', label: 'Auto-detect' },
  { code: 'en', label: 'English' },
  { code: 'fr', label: 'French / Francais' },
  { code: 'es', label: 'Spanish / Espanol' },
  { code: 'de', label: 'German / Deutsch' },
  { code: 'it', label: 'Italian / Italiano' },
  { code: 'pt', label: 'Portuguese / Portugues' },
  { code: 'nl', label: 'Dutch / Nederlands' },
  { code: 'ru', label: 'Russian' },
  { code: 'uk', label: 'Ukrainian' },
  { code: 'pl', label: 'Polish / Polski' },
  { code: 'cs', label: 'Czech / Cestina' },
  { code: 'sk', label: 'Slovak / Slovencina' },
  { code: 'hu', label: 'Hungarian / Magyar' },
  { code: 'ro', label: 'Romanian / Romana' },
  { code: 'bg', label: 'Bulgarian' },
  { code: 'hr', label: 'Croatian / Hrvatski' },
  { code: 'sr', label: 'Serbian' },
  { code: 'sl', label: 'Slovenian / Slovenscina' },
  { code: 'lv', label: 'Latvian / Latviesu' },
  { code: 'lt', label: 'Lithuanian / Lietuviu' },
  { code: 'et', label: 'Estonian / Eesti' },
  { code: 'sv', label: 'Swedish / Svenska' },
  { code: 'no', label: 'Norwegian / Norsk' },
  { code: 'da', label: 'Danish / Dansk' },
  { code: 'fi', label: 'Finnish / Suomi' },
  { code: 'el', label: 'Greek' },
  { code: 'tr', label: 'Turkish / Turkce' },
  { code: 'ar', label: 'Arabic' },
  { code: 'he', label: 'Hebrew' },
  { code: 'hi', label: 'Hindi' },
  { code: 'bn', label: 'Bengali' },
  { code: 'ta', label: 'Tamil' },
  { code: 'te', label: 'Telugu' },
  { code: 'mr', label: 'Marathi' },
  { code: 'gu', label: 'Gujarati' },
  { code: 'ur', label: 'Urdu' },
  { code: 'fa', label: 'Persian / Farsi' },
  { code: 'zh', label: 'Chinese' },
  { code: 'ja', label: 'Japanese' },
  { code: 'ko', label: 'Korean' },
  { code: 'th', label: 'Thai' },
  { code: 'vi', label: 'Vietnamese / Tieng Viet' },
  { code: 'id', label: 'Indonesian / Bahasa Indonesia' },
  { code: 'ms', label: 'Malay / Bahasa Melayu' },
  { code: 'tl', label: 'Filipino / Tagalog' },
  { code: 'sw', label: 'Swahili / Kiswahili' },
  { code: 'am', label: 'Amharic' },
  { code: 'yo', label: 'Yoruba' },
  { code: 'ha', label: 'Hausa' },
  { code: 'zu', label: 'Zulu / isiZulu' },
  { code: 'af', label: 'Afrikaans' },
  { code: 'ca', label: 'Catalan / Catala' },
  { code: 'eu', label: 'Basque / Euskara' },
  { code: 'gl', label: 'Galician / Galego' },
  { code: 'cy', label: 'Welsh / Cymraeg' },
  { code: 'ga', label: 'Irish / Gaeilge' },
  { code: 'ka', label: 'Georgian' },
  { code: 'hy', label: 'Armenian' },
  { code: 'az', label: 'Azerbaijani' },
  { code: 'uz', label: 'Uzbek' },
  { code: 'kk', label: 'Kazakh' },
  { code: 'mn', label: 'Mongolian' },
  { code: 'ne', label: 'Nepali' },
  { code: 'si', label: 'Sinhala' },
  { code: 'km', label: 'Khmer' },
  { code: 'lo', label: 'Lao' },
  { code: 'my', label: 'Burmese' },
] as const;

export type LanguageCode = (typeof SUPPORTED_LANGUAGES)[number]['code'];
