import type { IntegrationDefinition } from '@opensauria/types';

export const INTEGRATION_CATALOG: readonly IntegrationDefinition[] = [
  {
    id: 'notion',
    name: 'Notion',
    description: 'Workspace for notes, docs, and project management',
    icon: 'notion',
    category: 'productivity',
    authType: 'api_key',
    credentialKeys: ['apiKey'],
    mcpServer: {
      package: '@notionhq/notion-mcp-server',
      envMapping: { apiKey: 'OPENAPI_MCP_HEADERS' },
    },
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'Code hosting, issues, and pull requests',
    icon: 'github',
    category: 'development',
    authType: 'token',
    credentialKeys: ['token'],
    mcpServer: {
      package: '@modelcontextprotocol/server-github',
      envMapping: { token: 'GITHUB_PERSONAL_ACCESS_TOKEN' },
    },
  },
  {
    id: 'linear',
    name: 'Linear',
    description: 'Issue tracking and project management',
    icon: 'linear',
    category: 'project_management',
    authType: 'api_key',
    credentialKeys: ['apiKey'],
    mcpServer: {
      package: 'mcp-linear',
      envMapping: { apiKey: 'LINEAR_API_KEY' },
    },
  },
  {
    id: 'slack-tools',
    name: 'Slack',
    description: 'Team messaging and collaboration tools',
    icon: 'slack',
    category: 'communication',
    authType: 'token',
    credentialKeys: ['token'],
    mcpServer: {
      package: '@anthropic/mcp-server-slack',
      envMapping: { token: 'SLACK_BOT_TOKEN' },
    },
  },
  {
    id: 'google-drive',
    name: 'Google Drive',
    description: 'Cloud file storage and sharing',
    icon: 'googledrive',
    category: 'storage',
    authType: 'oauth',
    credentialKeys: ['clientId', 'clientSecret', 'refreshToken'],
    mcpServer: {
      package: '@anthropic/mcp-server-gdrive',
      envMapping: {
        clientId: 'GDRIVE_CLIENT_ID',
        clientSecret: 'GDRIVE_CLIENT_SECRET',
        refreshToken: 'GDRIVE_REFRESH_TOKEN',
      },
    },
  },
  {
    id: 'jira',
    name: 'Jira',
    description: 'Project tracking and agile management',
    icon: 'jira',
    category: 'project_management',
    authType: 'api_key',
    credentialKeys: ['url', 'email', 'apiKey'],
    mcpServer: {
      package: 'mcp-atlassian',
      envMapping: {
        url: 'JIRA_URL',
        email: 'JIRA_EMAIL',
        apiKey: 'JIRA_API_TOKEN',
      },
    },
  },
  {
    id: 'trello',
    name: 'Trello',
    description: 'Visual project boards and task management',
    icon: 'trello',
    category: 'project_management',
    authType: 'api_key',
    credentialKeys: ['apiKey', 'token'],
    mcpServer: {
      package: 'trello-mcp-server',
      envMapping: { apiKey: 'TRELLO_API_KEY', token: 'TRELLO_TOKEN' },
    },
  },
  {
    id: 'asana',
    name: 'Asana',
    description: 'Work management and team coordination',
    icon: 'asana',
    category: 'project_management',
    authType: 'token',
    credentialKeys: ['token'],
    mcpServer: {
      package: 'asana-mcp-server',
      envMapping: { token: 'ASANA_ACCESS_TOKEN' },
    },
  },
  {
    id: 'confluence',
    name: 'Confluence',
    description: 'Team wiki and documentation platform',
    icon: 'confluence',
    category: 'productivity',
    authType: 'api_key',
    credentialKeys: ['url', 'email', 'apiKey'],
    mcpServer: {
      package: 'mcp-atlassian',
      envMapping: {
        url: 'CONFLUENCE_URL',
        email: 'CONFLUENCE_EMAIL',
        apiKey: 'CONFLUENCE_API_TOKEN',
      },
    },
  },
  {
    id: 'sentry',
    name: 'Sentry',
    description: 'Error tracking and performance monitoring',
    icon: 'sentry',
    category: 'development',
    authType: 'token',
    credentialKeys: ['token'],
    mcpServer: {
      package: '@sentry/mcp-server-sentry',
      envMapping: { token: 'SENTRY_AUTH_TOKEN' },
    },
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    description: 'Relational database access and queries',
    icon: 'postgresql',
    category: 'development',
    authType: 'token',
    credentialKeys: ['connectionString'],
    mcpServer: {
      package: '@anthropic/mcp-server-postgres',
      envMapping: { connectionString: 'POSTGRES_CONNECTION_STRING' },
    },
  },
  {
    id: 'google-calendar',
    name: 'Google Calendar',
    description: 'Calendar events and scheduling',
    icon: 'googlecalendar',
    category: 'productivity',
    authType: 'oauth',
    credentialKeys: ['clientId', 'clientSecret', 'refreshToken'],
    mcpServer: {
      package: 'google-calendar-mcp',
      envMapping: {
        clientId: 'GCAL_CLIENT_ID',
        clientSecret: 'GCAL_CLIENT_SECRET',
        refreshToken: 'GCAL_REFRESH_TOKEN',
      },
    },
  },
  {
    id: 'figma',
    name: 'Figma',
    description: 'Design collaboration and prototyping',
    icon: 'figma',
    category: 'development',
    authType: 'token',
    credentialKeys: ['token'],
    mcpServer: {
      package: '@anthropic/mcp-server-figma',
      envMapping: { token: 'FIGMA_ACCESS_TOKEN' },
    },
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    description: 'CRM, marketing, and sales platform',
    icon: 'hubspot',
    category: 'crm',
    authType: 'api_key',
    credentialKeys: ['apiKey'],
    mcpServer: {
      package: 'hubspot-mcp-server',
      envMapping: { apiKey: 'HUBSPOT_API_KEY' },
    },
  },
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Payment processing and billing analytics',
    icon: 'stripe',
    category: 'analytics',
    authType: 'api_key',
    credentialKeys: ['apiKey'],
    mcpServer: {
      package: '@stripe/mcp-server-stripe',
      envMapping: { apiKey: 'STRIPE_API_KEY' },
    },
  },
] as const;
