import type { IntegrationDefinition } from '@sauria/types';

export const INTEGRATION_CATALOG: readonly IntegrationDefinition[] = [
  // ── Communication ──────────────────────────────
  {
    id: 'slack-tools',
    name: 'Slack',
    description: 'Team messaging and collaboration tools',
    icon: 'slack',
    category: 'communication',
    authType: 'token',
    credentialKeys: ['token'],
    mcpServer: {
      package: '@modelcontextprotocol/server-slack',
      envMapping: { token: 'SLACK_BOT_TOKEN' },
    },
  },
  {
    id: 'gmail',
    name: 'Gmail',
    description: 'Read, search, and send emails via Gmail',
    icon: 'gmail',
    category: 'communication',
    authType: 'oauth',
    credentialKeys: ['clientId', 'clientSecret', 'refreshToken'],
    mcpServer: {
      package: 'gmail-mcp-server',
      envMapping: {
        clientId: 'GMAIL_CLIENT_ID',
        clientSecret: 'GMAIL_CLIENT_SECRET',
        refreshToken: 'GMAIL_REFRESH_TOKEN',
      },
    },
  },
  {
    id: 'email-imap',
    name: 'Email (IMAP)',
    description: 'Read and send emails via IMAP/SMTP',
    icon: 'email',
    category: 'communication',
    authType: 'api_key',
    credentialKeys: ['imapHost', 'smtpHost', 'username', 'password'],
    mcpServer: {
      package: 'email-mcp-server',
      envMapping: {
        imapHost: 'EMAIL_IMAP_HOST',
        smtpHost: 'EMAIL_SMTP_HOST',
        username: 'EMAIL_USERNAME',
        password: 'EMAIL_PASSWORD',
      },
    },
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Community messaging and voice platform',
    icon: 'discord',
    category: 'communication',
    authType: 'token',
    credentialKeys: ['token'],
    mcpServer: {
      package: 'discord-mcp',
      envMapping: { token: 'DISCORD_TOKEN' },
    },
  },
  {
    id: 'twilio',
    name: 'Twilio',
    description: 'Programmable SMS, voice, and messaging APIs',
    icon: 'twilio',
    category: 'communication',
    authType: 'api_key',
    credentialKeys: ['accountSid', 'authToken'],
    mcpServer: {
      package: '@twilio-alpha/mcp',
      envMapping: {
        accountSid: 'TWILIO_ACCOUNT_SID',
        authToken: 'TWILIO_AUTH_TOKEN',
      },
    },
  },

  // ── Project Management ─────────────────────────
  {
    id: 'linear',
    name: 'Linear',
    description: 'Issue tracking and project management',
    icon: 'linear',
    category: 'project_management',
    authType: 'api_key',
    credentialKeys: ['apiKey'],
    mcpServer: {
      package: 'mcp-linear',
      envMapping: { apiKey: 'LINEAR_API_KEY' },
    },
  },
  {
    id: 'jira',
    name: 'Jira',
    description: 'Project tracking and agile management',
    icon: 'jira',
    category: 'project_management',
    authType: 'api_key',
    credentialKeys: ['siteName', 'email', 'apiKey'],
    mcpServer: {
      package: '@aashari/mcp-server-atlassian-jira',
      envMapping: {
        siteName: 'ATLASSIAN_SITE_NAME',
        email: 'ATLASSIAN_USER_EMAIL',
        apiKey: 'ATLASSIAN_API_TOKEN',
      },
    },
  },
  {
    id: 'trello',
    name: 'Trello',
    description: 'Visual project boards and task management',
    icon: 'trello',
    category: 'project_management',
    authType: 'api_key',
    credentialKeys: ['apiKey', 'token'],
    mcpServer: {
      package: 'trello-mcp-server',
      envMapping: { apiKey: 'TRELLO_API_KEY', token: 'TRELLO_TOKEN' },
    },
  },
  {
    id: 'asana',
    name: 'Asana',
    description: 'Work management and team coordination',
    icon: 'asana',
    category: 'project_management',
    authType: 'token',
    credentialKeys: ['token'],
    mcpServer: {
      package: '@roychri/mcp-server-asana',
      envMapping: { token: 'ASANA_ACCESS_TOKEN' },
    },
  },
  {
    id: 'clickup',
    name: 'ClickUp',
    description: 'All-in-one project management platform',
    icon: 'clickup',
    category: 'project_management',
    authType: 'api_key',
    credentialKeys: ['apiKey'],
    mcpServer: {
      package: 'clickup-mcp-server',
      envMapping: { apiKey: 'CLICKUP_API_KEY' },
    },
  },
  {
    id: 'todoist',
    name: 'Todoist',
    description: 'Task management and to-do lists',
    icon: 'todoist',
    category: 'project_management',
    authType: 'token',
    credentialKeys: ['token'],
    mcpServer: {
      package: '@abhiz123/todoist-mcp-server',
      envMapping: { token: 'TODOIST_API_TOKEN' },
    },
  },
  {
    id: 'monday',
    name: 'Monday.com',
    description: 'Work operating system for teams',
    icon: 'monday',
    category: 'project_management',
    authType: 'token',
    credentialKeys: ['token'],
    mcpServer: {
      package: '@mondaydotcomorg/monday-api-mcp',
      envMapping: { token: 'MONDAY_TOKEN' },
    },
  },
  {
    id: 'basecamp',
    name: 'Basecamp',
    description: 'Project management and team communication',
    icon: 'basecamp',
    category: 'project_management',
    authType: 'token',
    credentialKeys: ['token', 'accountId'],
    mcpServer: {
      package: 'basecamp-mcp-server',
      envMapping: {
        token: 'BASECAMP_ACCESS_TOKEN',
        accountId: 'BASECAMP_ACCOUNT_ID',
      },
    },
  },

  // ── Development ────────────────────────────────
  {
    id: 'github',
    name: 'GitHub',
    description: 'Code hosting, issues, and pull requests',
    icon: 'github',
    category: 'development',
    authType: 'token',
    credentialKeys: ['token'],
    mcpServer: {
      package: '@modelcontextprotocol/server-github',
      envMapping: { token: 'GITHUB_PERSONAL_ACCESS_TOKEN' },
    },
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    description: 'DevOps platform with Git repository management',
    icon: 'gitlab',
    category: 'development',
    authType: 'token',
    credentialKeys: ['token', 'url'],
    mcpServer: {
      package: '@modelcontextprotocol/server-gitlab',
      envMapping: { token: 'GITLAB_TOKEN', url: 'GITLAB_URL' },
    },
  },
  {
    id: 'bitbucket',
    name: 'Bitbucket',
    description: 'Git code hosting with CI/CD pipelines',
    icon: 'bitbucket',
    category: 'development',
    authType: 'api_key',
    credentialKeys: ['siteName', 'email', 'apiKey'],
    mcpServer: {
      package: '@aashari/mcp-server-atlassian-bitbucket',
      envMapping: {
        siteName: 'ATLASSIAN_SITE_NAME',
        email: 'ATLASSIAN_USER_EMAIL',
        apiKey: 'ATLASSIAN_API_TOKEN',
      },
    },
  },
  {
    id: 'circleci',
    name: 'CircleCI',
    description: 'Continuous integration and delivery platform',
    icon: 'circleci',
    category: 'development',
    authType: 'token',
    credentialKeys: ['token'],
    mcpServer: {
      package: '@circleci/mcp-server-circleci',
      envMapping: { token: 'CIRCLECI_TOKEN' },
    },
  },
  {
    id: 'vercel',
    name: 'Vercel',
    description: 'Frontend deployment and serverless platform',
    icon: 'vercel',
    category: 'development',
    authType: 'token',
    credentialKeys: ['token'],
    mcpServer: {
      package: 'vercel-mcp-server',
      envMapping: { token: 'VERCEL_TOKEN' },
    },
  },
  {
    id: 'netlify',
    name: 'Netlify',
    description: 'Web hosting and serverless backend services',
    icon: 'netlify',
    category: 'development',
    authType: 'token',
    credentialKeys: ['token'],
    mcpServer: {
      package: '@netlify/mcp',
      envMapping: { token: 'NETLIFY_TOKEN' },
    },
  },
  {
    id: 'docker',
    name: 'Docker',
    description: 'Container management and orchestration',
    icon: 'docker',
    category: 'development',
    authType: 'token',
    credentialKeys: ['host'],
    mcpServer: {
      package: 'mcp-server-docker',
      envMapping: { host: 'DOCKER_HOST' },
    },
  },
  {
    id: 'supabase',
    name: 'Supabase',
    description: 'Open source Firebase alternative with Postgres',
    icon: 'supabase',
    category: 'development',
    authType: 'api_key',
    credentialKeys: ['url', 'apiKey'],
    mcpServer: {
      package: '@supabase/mcp-server-supabase',
      envMapping: {
        url: 'SUPABASE_URL',
        apiKey: 'SUPABASE_SERVICE_ROLE_KEY',
      },
    },
  },

  // ── Productivity ───────────────────────────────
  {
    id: 'notion',
    name: 'Notion',
    description: 'Workspace for notes, docs, and project management',
    icon: 'notion',
    category: 'productivity',
    authType: 'api_key',
    credentialKeys: ['apiKey'],
    mcpServer: {
      package: '@notionhq/notion-mcp-server',
      envMapping: { apiKey: 'NOTION_TOKEN' },
    },
  },
  {
    id: 'confluence',
    name: 'Confluence',
    description: 'Team wiki and documentation platform',
    icon: 'confluence',
    category: 'productivity',
    authType: 'api_key',
    credentialKeys: ['siteName', 'email', 'apiKey'],
    mcpServer: {
      package: '@aashari/mcp-server-atlassian-confluence',
      envMapping: {
        siteName: 'ATLASSIAN_SITE_NAME',
        email: 'ATLASSIAN_USER_EMAIL',
        apiKey: 'ATLASSIAN_API_TOKEN',
      },
    },
  },
  {
    id: 'google-calendar',
    name: 'Google Calendar',
    description: 'Calendar events and scheduling',
    icon: 'googlecalendar',
    category: 'productivity',
    authType: 'oauth',
    credentialKeys: ['clientId', 'clientSecret', 'refreshToken'],
    mcpServer: {
      package: 'google-calendar-mcp',
      envMapping: {
        clientId: 'GCAL_CLIENT_ID',
        clientSecret: 'GCAL_CLIENT_SECRET',
        refreshToken: 'GCAL_REFRESH_TOKEN',
      },
    },
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    description: 'Knowledge base and note-taking with Markdown',
    icon: 'obsidian',
    category: 'productivity',
    authType: 'api_key',
    credentialKeys: ['vaultPath'],
    mcpServer: {
      package: 'obsidian-mcp-server',
      envMapping: { vaultPath: 'OBSIDIAN_VAULT_PATH' },
    },
  },
  {
    id: 'airtable',
    name: 'Airtable',
    description: 'Spreadsheet-database hybrid for teams',
    icon: 'airtable',
    category: 'productivity',
    authType: 'api_key',
    credentialKeys: ['apiKey'],
    mcpServer: {
      package: 'airtable-mcp-server',
      envMapping: { apiKey: 'AIRTABLE_API_KEY' },
    },
  },
  {
    id: 'evernote',
    name: 'Evernote',
    description: 'Note-taking and personal organization',
    icon: 'evernote',
    category: 'productivity',
    authType: 'token',
    credentialKeys: ['token'],
    mcpServer: {
      package: '@verygoodplugins/mcp-evernote',
      envMapping: { token: 'EVERNOTE_TOKEN' },
    },
  },

  // ── Infrastructure ─────────────────────────────
  {
    id: 'azure',
    name: 'Azure',
    description: 'Microsoft Azure cloud computing platform',
    icon: 'azure',
    category: 'infrastructure',
    authType: 'api_key',
    credentialKeys: ['subscriptionId', 'tenantId', 'clientId', 'clientSecret'],
    mcpServer: {
      package: '@azure/mcp',
      envMapping: {
        subscriptionId: 'AZURE_SUBSCRIPTION_ID',
        tenantId: 'AZURE_TENANT_ID',
        clientId: 'AZURE_CLIENT_ID',
        clientSecret: 'AZURE_CLIENT_SECRET',
      },
    },
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    description: 'CDN, DNS, and edge computing platform',
    icon: 'cloudflare',
    category: 'infrastructure',
    authType: 'api_key',
    credentialKeys: ['apiKey'],
    mcpServer: {
      package: '@cloudflare/mcp-server-cloudflare',
      envMapping: { apiKey: 'CLOUDFLARE_API_KEY' },
    },
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    description: 'Container orchestration and cluster management',
    icon: 'kubernetes',
    category: 'infrastructure',
    authType: 'token',
    credentialKeys: ['kubeconfig'],
    mcpServer: {
      package: 'kubernetes-mcp-server',
      envMapping: { kubeconfig: 'KUBECONFIG' },
    },
  },
  {
    id: 'aws',
    name: 'AWS',
    description: 'Amazon Web Services cloud platform',
    icon: 'aws',
    category: 'infrastructure',
    authType: 'api_key',
    credentialKeys: ['accessKeyId', 'secretAccessKey', 'region'],
    mcpServer: {
      package: '@aws/mcp',
      envMapping: {
        accessKeyId: 'AWS_ACCESS_KEY_ID',
        secretAccessKey: 'AWS_SECRET_ACCESS_KEY',
        region: 'AWS_REGION',
      },
    },
  },
  {
    id: 'google-cloud',
    name: 'Google Cloud',
    description: 'Google Cloud Platform services and APIs',
    icon: 'googlecloud',
    category: 'infrastructure',
    authType: 'api_key',
    credentialKeys: ['credentialsPath', 'project'],
    mcpServer: {
      package: '@google-cloud/gcloud-mcp',
      envMapping: {
        credentialsPath: 'GOOGLE_APPLICATION_CREDENTIALS',
        project: 'GCLOUD_PROJECT',
      },
    },
  },

  // ── Monitoring ─────────────────────────────────
  {
    id: 'sentry',
    name: 'Sentry',
    description: 'Error tracking and performance monitoring',
    icon: 'sentry',
    category: 'monitoring',
    authType: 'token',
    credentialKeys: ['token'],
    mcpServer: {
      package: '@sentry/mcp-server',
      envMapping: { token: 'SENTRY_AUTH_TOKEN' },
    },
  },
  {
    id: 'datadog',
    name: 'Datadog',
    description: 'Cloud monitoring and security platform',
    icon: 'datadog',
    category: 'monitoring',
    authType: 'api_key',
    credentialKeys: ['apiKey', 'appKey'],
    mcpServer: {
      package: 'datadog-mcp-server',
      envMapping: { apiKey: 'DATADOG_API_KEY', appKey: 'DATADOG_APP_KEY' },
    },
  },
  {
    id: 'grafana',
    name: 'Grafana',
    description: 'Observability dashboards and alerting',
    icon: 'grafana',
    category: 'monitoring',
    authType: 'api_key',
    credentialKeys: ['url', 'apiKey'],
    mcpServer: {
      package: 'mcp-grafana',
      envMapping: { url: 'GRAFANA_URL', apiKey: 'GRAFANA_API_KEY' },
    },
  },
  {
    id: 'pagerduty',
    name: 'PagerDuty',
    description: 'Incident management and on-call scheduling',
    icon: 'pagerduty',
    category: 'monitoring',
    authType: 'token',
    credentialKeys: ['token'],
    mcpServer: {
      package: 'pagerduty-mcp-server',
      envMapping: { token: 'PAGERDUTY_API_TOKEN' },
    },
  },
  {
    id: 'prometheus',
    name: 'Prometheus',
    description: 'Metrics collection and alerting toolkit',
    icon: 'prometheus',
    category: 'monitoring',
    authType: 'token',
    credentialKeys: ['url'],
    mcpServer: {
      package: '@prom-mcp/prometheus-mcp-server',
      envMapping: { url: 'PROMETHEUS_URL' },
    },
  },

  // ── E-commerce ─────────────────────────────────
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Payment processing and billing analytics',
    icon: 'stripe',
    category: 'ecommerce',
    authType: 'api_key',
    credentialKeys: ['apiKey'],
    mcpServer: {
      package: '@stripe/mcp',
      envMapping: { apiKey: 'STRIPE_SECRET_KEY' },
    },
  },
  {
    id: 'paypal',
    name: 'PayPal',
    description: 'Online payments and money transfers',
    icon: 'paypal',
    category: 'ecommerce',
    authType: 'api_key',
    credentialKeys: ['accessToken'],
    mcpServer: {
      package: '@paypal/mcp',
      envMapping: {
        accessToken: 'PAYPAL_ACCESS_TOKEN',
      },
    },
  },
  {
    id: 'shopify',
    name: 'Shopify',
    description: 'E-commerce platform for online stores',
    icon: 'shopify',
    category: 'ecommerce',
    authType: 'api_key',
    credentialKeys: ['storeUrl', 'accessToken'],
    mcpServer: {
      package: '@shopify/dev-mcp',
      envMapping: {
        storeUrl: 'SHOPIFY_STORE_URL',
        accessToken: 'SHOPIFY_ACCESS_TOKEN',
      },
    },
  },

  // ── Design ─────────────────────────────────────
  {
    id: 'figma',
    name: 'Figma',
    description: 'Design collaboration and prototyping',
    icon: 'figma',
    category: 'design',
    authType: 'token',
    credentialKeys: ['token'],
    mcpServer: {
      package: 'figma-developer-mcp',
      envMapping: { token: 'FIGMA_ACCESS_TOKEN' },
    },
  },
  {
    id: 'canva',
    name: 'Canva',
    description: 'Online design and visual content creation',
    icon: 'canva',
    category: 'design',
    authType: 'oauth',
    credentialKeys: ['clientId', 'clientSecret'],
    mcpServer: {
      package: '@canva/cli',
      envMapping: {
        clientId: 'CANVA_CLIENT_ID',
        clientSecret: 'CANVA_CLIENT_SECRET',
      },
    },
  },
  {
    id: 'miro',
    name: 'Miro',
    description: 'Online collaborative whiteboard platform',
    icon: 'miro',
    category: 'design',
    authType: 'token',
    credentialKeys: ['token'],
    mcpServer: {
      package: '@llmindset/mcp-miro',
      envMapping: { token: 'MIRO_TOKEN' },
    },
  },

  // ── Data ───────────────────────────────────────
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    description: 'Relational database access and queries',
    icon: 'postgresql',
    category: 'data',
    authType: 'token',
    credentialKeys: ['connectionString'],
    mcpServer: {
      package: '@modelcontextprotocol/server-postgres',
      envMapping: { connectionString: 'POSTGRES_CONNECTION_STRING' },
    },
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    description: 'Document database for modern applications',
    icon: 'mongodb',
    category: 'data',
    authType: 'token',
    credentialKeys: ['connectionString'],
    mcpServer: {
      package: 'mongodb-mcp-server',
      envMapping: { connectionString: 'MONGODB_CONNECTION_STRING' },
    },
  },
  {
    id: 'mysql',
    name: 'MySQL',
    description: 'Open source relational database',
    icon: 'mysql',
    category: 'data',
    authType: 'token',
    credentialKeys: ['connectionString'],
    mcpServer: {
      package: '@naganpm/mysql-mcp-server',
      envMapping: { connectionString: 'MYSQL_CONNECTION_STRING' },
    },
  },
  {
    id: 'redis',
    name: 'Redis',
    description: 'In-memory data store and cache',
    icon: 'redis',
    category: 'data',
    authType: 'token',
    credentialKeys: ['url'],
    mcpServer: {
      package: '@gongrzhe/server-redis-mcp',
      envMapping: { url: 'REDIS_URL' },
    },
  },
  {
    id: 'elasticsearch',
    name: 'Elasticsearch',
    description: 'Distributed search and analytics engine',
    icon: 'elasticsearch',
    category: 'data',
    authType: 'api_key',
    credentialKeys: ['url', 'apiKey'],
    mcpServer: {
      package: '@elastic/mcp-server-elasticsearch',
      envMapping: { url: 'ES_URL', apiKey: 'ES_API_KEY' },
    },
  },
  {
    id: 'bigquery',
    name: 'BigQuery',
    description: 'Serverless data warehouse for analytics',
    icon: 'bigquery',
    category: 'data',
    authType: 'api_key',
    credentialKeys: ['credentialsPath', 'projectId'],
    mcpServer: {
      package: 'mcp-server-bigquery',
      envMapping: {
        credentialsPath: 'GOOGLE_APPLICATION_CREDENTIALS',
        projectId: 'GCP_PROJECT_ID',
      },
    },
  },

  // ── CRM ────────────────────────────────────────
  {
    id: 'hubspot',
    name: 'HubSpot',
    description: 'CRM, marketing, and sales platform',
    icon: 'hubspot',
    category: 'crm',
    authType: 'api_key',
    credentialKeys: ['apiKey'],
    mcpServer: {
      package: '@hubspot/mcp-server',
      envMapping: { apiKey: 'HUBSPOT_PRIVATE_APP_TOKEN' },
    },
  },
  {
    id: 'pipedrive',
    name: 'Pipedrive',
    description: 'Sales CRM and pipeline management',
    icon: 'pipedrive',
    category: 'crm',
    authType: 'api_key',
    credentialKeys: ['apiKey'],
    mcpServer: {
      package: '@iamsamuelfraga/mcp-pipedrive',
      envMapping: { apiKey: 'PIPEDRIVE_API_KEY' },
    },
  },
  {
    id: 'salesforce',
    name: 'Salesforce',
    description: 'Enterprise CRM and business platform',
    icon: 'salesforce',
    category: 'crm',
    authType: 'oauth',
    credentialKeys: ['instanceUrl', 'clientId', 'clientSecret'],
    mcpServer: {
      package: '@salesforce/mcp',
      envMapping: {
        instanceUrl: 'SALESFORCE_INSTANCE_URL',
        clientId: 'SALESFORCE_CLIENT_ID',
        clientSecret: 'SALESFORCE_CLIENT_SECRET',
      },
    },
  },

  // ── Support ────────────────────────────────────
  {
    id: 'zendesk',
    name: 'Zendesk',
    description: 'Customer support and helpdesk platform',
    icon: 'zendesk',
    category: 'support',
    authType: 'api_key',
    credentialKeys: ['domain', 'apiToken'],
    mcpServer: {
      package: '@sshadows/zendesk-mcp-server',
      envMapping: { domain: 'ZENDESK_DOMAIN', apiToken: 'ZENDESK_API_TOKEN' },
    },
  },
  {
    id: 'intercom',
    name: 'Intercom',
    description: 'Customer messaging and engagement platform',
    icon: 'intercom',
    category: 'support',
    authType: 'token',
    credentialKeys: ['token'],
    mcpServer: {
      package: 'mcp-intercom',
      envMapping: { token: 'INTERCOM_API_TOKEN' },
    },
  },

  // ── Automation ─────────────────────────────────
  {
    id: 'zapier',
    name: 'Zapier',
    description: 'No-code automation between web apps',
    icon: 'zapier',
    category: 'automation',
    authType: 'api_key',
    credentialKeys: ['apiKey'],
    mcpServer: {
      package: '@zapier/zapier-sdk-mcp',
      envMapping: { apiKey: 'ZAPIER_API_KEY' },
    },
  },
  {
    id: 'n8n',
    name: 'n8n',
    description: 'Open source workflow automation tool',
    icon: 'n8n',
    category: 'automation',
    authType: 'api_key',
    credentialKeys: ['url', 'apiKey'],
    mcpServer: {
      package: 'n8n-mcp',
      envMapping: { url: 'N8N_URL', apiKey: 'N8N_API_KEY' },
    },
  },

  // ── Content ────────────────────────────────────
  {
    id: 'contentful',
    name: 'Contentful',
    description: 'Headless CMS for digital experiences',
    icon: 'contentful',
    category: 'content',
    authType: 'api_key',
    credentialKeys: ['spaceId', 'accessToken'],
    mcpServer: {
      package: '@contentful/mcp-server',
      envMapping: {
        spaceId: 'CONTENTFUL_SPACE_ID',
        accessToken: 'CONTENTFUL_ACCESS_TOKEN',
      },
    },
  },
  {
    id: 'sanity',
    name: 'Sanity',
    description: 'Structured content platform for developers',
    icon: 'sanity',
    category: 'content',
    authType: 'token',
    credentialKeys: ['projectId', 'token'],
    mcpServer: {
      package: '@sanity/mcp-server',
      envMapping: {
        projectId: 'SANITY_PROJECT_ID',
        token: 'SANITY_TOKEN',
      },
    },
  },

  // ── Storage ────────────────────────────────────
  {
    id: 'google-drive',
    name: 'Google Drive',
    description: 'Cloud file storage and sharing',
    icon: 'googledrive',
    category: 'storage',
    authType: 'oauth',
    credentialKeys: ['clientId', 'clientSecret', 'refreshToken'],
    mcpServer: {
      package: 'gdrive-mcp',
      envMapping: {
        clientId: 'GDRIVE_CLIENT_ID',
        clientSecret: 'GDRIVE_CLIENT_SECRET',
        refreshToken: 'GDRIVE_REFRESH_TOKEN',
      },
    },
  },

  // ── Social ─────────────────────────────────────
  {
    id: 'x',
    name: 'X (Twitter)',
    description: 'Social media posting and monitoring',
    icon: 'x',
    category: 'social',
    authType: 'api_key',
    credentialKeys: ['bearerToken'],
    mcpServer: {
      package: '@iflow-mcp/x-mcp-server',
      envMapping: { bearerToken: 'TWITTER_BEARER_TOKEN' },
    },
  },
  {
    id: 'reddit',
    name: 'Reddit',
    description: 'Community discussions and content aggregation',
    icon: 'reddit',
    category: 'social',
    authType: 'oauth',
    credentialKeys: ['clientId', 'clientSecret', 'userAgent'],
    mcpServer: {
      package: 'reddit-mcp-server',
      envMapping: {
        clientId: 'REDDIT_CLIENT_ID',
        clientSecret: 'REDDIT_CLIENT_SECRET',
        userAgent: 'REDDIT_USER_AGENT',
      },
    },
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    description: 'Professional networking and content sharing',
    icon: 'linkedin',
    category: 'social',
    authType: 'oauth',
    credentialKeys: ['clientId', 'clientSecret'],
    mcpServer: {
      package: 'linkedin-mcp-server',
      envMapping: {
        clientId: 'LINKEDIN_CLIENT_ID',
        clientSecret: 'LINKEDIN_CLIENT_SECRET',
      },
    },
  },
  {
    id: 'youtube',
    name: 'YouTube',
    description: 'Video platform transcripts and metadata',
    icon: 'youtube',
    category: 'social',
    authType: 'api_key',
    credentialKeys: ['apiKey'],
    mcpServer: {
      package: '@iflow-mcp/mcp-youtube-transcript',
      envMapping: { apiKey: 'YOUTUBE_API_KEY' },
    },
  },

  // ── Marketing ──────────────────────────────────
  {
    id: 'mailchimp',
    name: 'Mailchimp',
    description: 'Email marketing and audience management',
    icon: 'mailchimp',
    category: 'marketing',
    authType: 'api_key',
    credentialKeys: ['apiKey', 'serverPrefix'],
    mcpServer: {
      package: '@agentx-ai/mailchimp-mcp-server',
      envMapping: {
        apiKey: 'MAILCHIMP_API_KEY',
        serverPrefix: 'MAILCHIMP_SERVER_PREFIX',
      },
    },
  },
  {
    id: 'brevo',
    name: 'Brevo',
    description: 'Email marketing and transactional messaging',
    icon: 'brevo',
    category: 'marketing',
    authType: 'api_key',
    credentialKeys: ['apiKey'],
    mcpServer: {
      package: '@houtini/brevo-mcp',
      envMapping: { apiKey: 'BREVO_API_KEY' },
    },
  },
  {
    id: 'sendgrid',
    name: 'SendGrid',
    description: 'Email delivery and marketing campaigns',
    icon: 'sendgrid',
    category: 'marketing',
    authType: 'api_key',
    credentialKeys: ['apiKey'],
    mcpServer: {
      package: 'sendgrid-mcp',
      envMapping: { apiKey: 'SENDGRID_API_KEY' },
    },
  },

  // ── CMS ────────────────────────────────────────
  {
    id: 'wordpress',
    name: 'WordPress',
    description: 'Content management and publishing platform',
    icon: 'wordpress',
    category: 'cms',
    authType: 'api_key',
    credentialKeys: ['url', 'username', 'password'],
    mcpServer: {
      package: 'mcp-wordpress',
      envMapping: {
        url: 'WORDPRESS_URL',
        username: 'WORDPRESS_USERNAME',
        password: 'WORDPRESS_PASSWORD',
      },
    },
  },
  {
    id: 'ghost',
    name: 'Ghost',
    description: 'Modern publishing and newsletter platform',
    icon: 'ghost',
    category: 'cms',
    authType: 'api_key',
    credentialKeys: ['url', 'apiKey'],
    mcpServer: {
      package: '@mtane0412/ghost-mcp-server',
      envMapping: { url: 'GHOST_API_URL', apiKey: 'GHOST_API_KEY' },
    },
  },
] as const;
